name: Check for malicious npm dependencies

on:
  push:

  workflow_dispatch:

jobs:
  mal_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: h4sh5/npm-mal-feed-check@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}